import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Scorer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          enableSystem
          defaultTheme='system'
          disableTransitionOnChange
        >
          {/* <Nav /> */}
          <main className='max-w-7xl mx-auto  h-[calc(100dvh-4.5rem)]'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
